version: '2'

volumes:
  mysql-data:
    driver: local

services:
  backend:
    image: ambientum/php:7.1-caddy
    volumes:
      - ./backend:/var/www/app
    ports:
      - 8888:8080
    links:
      - db
  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}